### ISSUE TITLE
Fail to run flutter run on iOS Simulator

### ISSUE THREAD

**Issue by yhyuan** [jhomlala/feather#13]
Hi 

When I tried to run flutter run with a ios simuator. I got the following error. 

Launching lib/main.dart on iPhone XR in debug mode...
Starting Xcode build...
 ├─Assembling Flutter resources...                    2.2s

 └─Compiling, linking and signing...                  6.3s

Xcode build done.                                           10.8s
 8.2s
Syncing files to device iPhone XR...
flutter: [FINE][2019-01-25 22:28:42.215502][WeatherBloc]: Setup timer
flutter: [FINE][2019-01-25 22:28:42.231808][WeatherBloc]: Fetch weather for user location
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b1b91bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010a757735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b1b8d29 -[NSException raise] + 9
	3   permission_handler                  0x000000010a0c3e14 $S18permission_handler26LocationPermissionStrategyC07requestD00A017completionHandleryAA0D5GroupO_yAA0D6StatusOctF + 3108
	4   permission_handler                  0x000000010a0c514b $S18permission_handler26LocationPermissionStrategyCAA0dE0A2aDP07requestD00A017completionHandleryAA0D5GroupO_yAA0D6StatusOctFTW + 43
	5   permission_handler                  0x000000010a0c8199 $S18permission_handler17PermissionManagerC1<…>
Lost connection to device.

**Comment by jhomlala** [comment]
Hi, currently I'm unable to fix this bug, because I don't have access to Mac computer. I'll try fix this asap.
