### ISSUE TITLE
Change location screen?

### ISSUE THREAD

**Issue by thewithz** [jhomlala/feather#19]
Currently, the location service get *close* to where I live, but still pretty far away such that the weather could
potentially be different where I am, compared to what feather is reporting to me.

**Comment by thewithz** [comment]
It appears that even on the highest accuracy setting, Geolocator still isn't very good :thinking:

**Comment by thewithz** [comment]
Since this seems like a localized issue, feel free to close this and I'll just change the source before I build the apk

**Comment by jhomlala** [comment]
Can you check app logs and see requests to Open Weather API? There should be your lat and long coordinates. Please check if these coordinates are valid for your location.

**Comment by thewithz** [comment]
my `com.jhomlala.feather/files` directory is empty. Is that the correct location to find the logs?

**Comment by jhomlala** [comment]
No, there is no logger which logs to file.  Logs are printed in console. You can try run app in Android Studio or VS Code to see logs.

**Comment by thewithz** [comment]
running it on android studio, google says the distance between my given coordinates from geolocator are 3400 meters from my exact location. 

that's a good deal bigger than the `0 - 100m` the the geolocator plugin claims

**Comment by jhomlala** [comment]
Well, my location is pretty accurate. Detected location was 10-20 meters from my real location. I think that 3400 meters will not affect the weather that are being received from Open Weather API.

**Comment by jhomlala** [comment]
Anyway we can try use another library for geo location. Do you know any libraries that will work better than GeoLocator?

**Comment by thewithz** [comment]
None that are free. I can live some degree of error. I'll tinker with the
settings a little longer and see what I can do. If nothing works I'll just
hard code it in .

**Comment by jhomlala** [comment]
Well we can try adding feature which allows to setup lat/long manually.
